# Generated by Django 3.0 on 2019-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_auto_20191218_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_emoployess',
            name='profile_pic',
            field=models.FileField(default='avatar.png', upload_to='hrms/img/'),
        ),
    ]
