# Generated by Django 3.0 on 2019-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_auto_20191219_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_emoployess',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_emoployess',
            name='passport_ex_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_emoployess',
            name='passport_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_emoployess',
            name='religion',
            field=models.CharField(max_length=50),
        ),
    ]
