# Generated by Django 3.0 on 2019-12-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_auto_20191222_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('ticket_id', models.CharField(max_length=50)),
                ('assign_staff', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('cc', models.CharField(max_length=50)),
                ('assign', models.CharField(max_length=50)),
                ('followers', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
