# Generated by Django 3.0 on 2019-12-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrms.Add_Emoployess'),
            preserve_default=False,
        ),
    ]
