# Generated by Django 3.0 on 2019-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_ticket_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_emoployess',
            old_name='bank_name',
            new_name='complete_date',
        ),
        migrations.RenameField(
            model_name='add_emoployess',
            old_name='ifsc_code',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='add_emoployess',
            old_name='pan_no',
            new_name='p_from',
        ),
        migrations.RemoveField(
            model_name='add_emoployess',
            name='acc_no',
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='c_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='dob',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='grade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='institute',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='mobile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='p_to',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='position',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='relationship',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='startind_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='subject',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
