# Generated by Django 3.0 on 2019-12-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_department_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_emoployess',
            name='acc_num',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='bank_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='ifsc',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_emoployess',
            name='pan_no',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
